Check for self._collection too
since we use it for get_item. This avoids

Failed HEAD for /asfd/
Traceback (most recent call last):
  File "/var/scratch/debian/calypso/calypso/calypso/__init__.py", line 236, in do_HEAD
    item = self._collection.get_item(item_name)
AttributeError: 'NoneType' object has no attribute 'get_item'

and we return 404 instead of 400.

Signed-off-by: Keith Packard <keithp@keithp.com>