setup: Fallback to version 0.0.1 if we cannot import calypso
Mostly due to dependency problems, i.e.:
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    import calypso
  File "/home/muelli/vcs/calypso/calypso/__init__.py", line 54, in <module>
    from calypso import acl, config, webdav, xmlutils
  File "/home/muelli/vcs/calypso/calypso/webdav.py", line 36, in <module>
    import vobject
ImportError: No module named vobject