ical: Fixed an exception in create_file which used an undefined variable
An exception used "path" which was in the try block and hence not available.
Fixes the following issue:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 639, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 337, in handle
    self.handle_one_request()
  File "/home/muelli/git/calypso/calypso/__init__.py", line 155, in handle_one_request
    method()
  File "/home/muelli/git/calypso/calypso/__init__.py", line 123, in <lambda>
    check_rights = lambda function: lambda request: _check(request, function)
  File "/home/muelli/git/calypso/calypso/__init__.py", line 73, in _check
    function(request)
  File "/home/muelli/git/calypso/calypso/__init__.py", line 322, in do_PUT
    xmlutils.put(self.path, ical_request, self._calendar)
  File "/home/muelli/git/calypso/calypso/xmlutils.py", line 209, in put
    calendar.append(name, ical_request)
  File "/home/muelli/git/calypso/calypso/ical.py", line 286, in append
    self.create_file(new_item)
  File "/home/muelli/git/calypso/calypso/ical.py", line 235, in create_file
    print "Failed to create %s: %s" % (path % ex)
UnboundLocalError: local variable 'path' referenced before assignment
----------------------------------------